name: Enable Infrastructure via Terraform

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8
      - name: Create Terraform Backend
        run: |
          cat << EOF > iac/backend
          skip_credentials_validation = true
          skip_region_validation = true
          bucket = "cfe-ai-as-an-api"
          key    = "ai-as-an-api.tfstate"
          region = "${{ secrets.REGION_NAME }}"  
          endpoint = "us-southeast-1.linodeobjects.com"
          access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
          secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          EOF
      - name: Create Terraform Backend
        run: |
          cat << EOF > iac/terraform.tfvars
          linode_api_token="${{ secrets.LINODE_API_TOKEN }}"
          root_user_pw="${{ secrets.LINODE_INSTANCE_USER_PW }}"
          node_count="${{ secrets.TERRAFORM_NODE_COUNT }}"
          git_repo="${{ secrets.TERRAFORM_GIT_REPO }}"
          commit_id="${GITHUB_SHA::6}"
          EOF
      - name: Terraform Init
        run: terraform -chdir=./iac init -backend-config=backend
      - name: Apply Terraform Infrastrucure
        if: ${{ secrets.TERRAFORM_DESTROY != '1' }}
        run: terraform -chdir=./iac apply -auto-approve
      - name: Destroy Terraform Infrastrucure
        if: ${{ secrets.TERRAFORM_DESTROY != '1' }}
        run: terraform -chdir=./iac apply -destroy -auto-approve
      - name: Update Instance 1
        if: ${{ secrets.TERRAFORM_UPDATE == '1' }}
        run: terraform -chdir=./iac apply -auto-approve -replace="linode_instance.cfe_ai_instance[0]"
        continue-on-error: true
      - name: Update Instance 2
        if: ${{ secrets.TERRAFORM_UPDATE == '1' }}
        run: terraform -chdir=./iac apply -auto-approve -replace="linode_instance.cfe_ai_instance[1]"
        continue-on-error: true
      - name: Update Nodebalancer
        if: ${{ secrets.TERRAFORM_UPDATE == '1' }}
        run: terraform -chdir=./iac apply -auto-approve -replace="linode_instance.pycfeai"